id: trained_facilitator_infrastructure_to_standardized_recovery_support_quality
name: Trained Facilitator Infrastructure in Mutual Support Groups → Standardized Quality
  of Recovery Support
from_node:
  node_id: trained_facilitator_infrastructure
  node_name: Trained Facilitator Infrastructure in Mutual Support Groups
to_node:
  node_id: standardized_recovery_support_quality
  node_name: Standardized Quality of Recovery Support
direction: positive
category: healthcare_access
mechanism_pathway:
- 'Step 1: SMART Recovery organizational structure ensures all groups are led by trained
  facilitators rather than relying solely on peer leadership'
- 'Step 2: Facilitator training provides standardized approach to delivering Self-Management
  and Recovery Training methodology'
- 'Step 3: Trained facilitators create organizational capacity to implement systematic
  practices like routine outcome monitoring'
- 'Step 4: Standardized facilitation reduces variability in quality and content of
  support across different groups and locations'
- 'Step 5: Consistent, quality support across mutual support network improves reliability
  of recovery resources available to participants'
evidence:
  quality_rating: C
  n_studies: 1
  primary_citation: 'P. Kelly et al. 2020. "Feasibility of a Mobile Health App for
    Routine Outcome Monitoring and Feedback in Mutual Support Groups Coordinated by
    SMART Recovery Australia: Protocol for a Pilot Study." *JMIR Research Protocols*.
    https://doi.org/10.2196/15113'
last_updated: '2025-12-02'
version: '1.0'
llm_metadata:
  extracted_by: claude-sonnet-4-5-20250929
  extraction_date: '2025-12-02T18:12:05.836603'
  batch_id: msgbatch_01AKnPJgzm7Fk9qubgAz9GaD
moderators:
- name: organizational_coordination
  direction: strengthens
  strength: strong
  description: SMART Recovery Australia's centralized coordination enables consistent
    facilitator training and support across multiple sites
- name: facilitator_retention_turnover
  direction: strengthens
  strength: moderate
  description: Sustainability of trained facilitator infrastructure depends on retention
    and ongoing training systems
- name: integration_of_technology_tools
  direction: strengthens
  strength: moderate
  description: Trained facilitators' ability to incorporate new tools like ROM apps
    into practice affects implementation success
