id: trained_immunity_induction_to_inflammatory_disorder_progression
name: Trained Immunity Induction → Inflammatory Disorder Progression
from_node:
  node_id: trained_immunity_induction
  node_name: Trained Immunity Induction
to_node:
  node_id: inflammatory_disorder_progression
  node_name: Inflammatory Disorder Progression
direction: positive
category: biological
mechanism_pathway:
- 'Step 1: Inappropriate or excessive induction of trained immunity occurs in innate
  immune cells'
- 'Step 2: Trained immunity causes epigenetic and metabolic alterations that increase
  inflammatory capacity of myeloid cells'
- 'Step 3: Heightened inflammatory responsiveness leads to exaggerated immune responses
  to subsequent challenges'
- 'Step 4: Sustained or excessive inflammation contributes to progression and worsening
  of inflammatory pathologies'
evidence:
  quality_rating: C
  n_studies: null
  primary_citation: 'Trim Lajqi et al. 2023. "Training vs. Tolerance: The Yin/Yang
    of the Innate Immune System." *Biomedicines*. https://doi.org/10.3390/biomedicines11030766'
last_updated: '2025-12-02'
version: '1.0'
llm_metadata:
  extracted_by: claude-sonnet-4-5-20250929
  extraction_date: '2025-12-02T18:12:07.107521'
  batch_id: msgbatch_01AKnPJgzm7Fk9qubgAz9GaD
moderators:
- name: appropriateness_of_induction
  direction: strengthens
  strength: strong
  description: Inappropriate or maladaptive induction of trained immunity strengthens
    the pathway to inflammatory disorder, while appropriate induction provides protection
    against infections
