id: product_classification_systems_to_alcohol_related_health_risks
name: Current Alcohol Product Classification Systems → Alcohol-Related Health Risks
from_node:
  node_id: product_classification_systems
  node_name: Current Alcohol Product Classification Systems
to_node:
  node_id: alcohol_related_health_risks
  node_name: Alcohol-Related Health Risks
direction: positive
category: political
mechanism_pathway:
- 'Step 1: Current regulatory classifications categorize products by beverage type
  (beer, wine, spirits) rather than alcohol content or risk profile'
- 'Step 2: This allows manufacturers to produce high-ABV products (e.g., 9.0% ABV
  malt liquor, FAB) that are regulated and taxed as ''beer'' rather than spirits'
- 'Step 3: Lower tax rates and less stringent regulations for beer-classified products
  result in lower retail prices despite equivalent or higher alcohol delivery'
- 'Step 4: Population exposure to high-risk products increases, elevating rates of
  acute intoxication, alcohol dependence, and chronic health harms'
evidence:
  quality_rating: C
  n_studies: 1
  primary_citation: 'Matthew E Rossheim et al. 2025. "An online assessment of pricing
    for ready-to-drink alcohol products: Implications for risk and policy solutions.."
    *Alcohol, clinical & experimental research*. https://doi.org/10.1111/acer.15491'
last_updated: '2025-12-02'
version: '1.0'
llm_metadata:
  extracted_by: claude-sonnet-4-5-20250929
  extraction_date: '2025-12-02T18:12:05.125437'
  batch_id: msgbatch_01AKnPJgzm7Fk9qubgAz9GaD
moderators:
- name: abv_thresholds
  direction: strengthens
  strength: strong
  description: Products with ABV significantly higher than traditional beer (9.0%
    vs 4-5% typical) but classified as beer create greatest regulatory mismatch and
    health risk
- name: regulatory_capture
  direction: strengthens
  strength: moderate
  description: Alcohol industry influence on classification systems perpetuates outdated
    categories that favor manufacturer interests over public health
