id: trained_immunity_induction_to_secondary_infection_protection
name: Trained Immunity Induction → Secondary Infection Protection
from_node:
  node_id: trained_immunity_induction
  node_name: Trained Immunity Induction
to_node:
  node_id: secondary_infection_protection
  node_name: Secondary Infection Protection
direction: positive
category: biological
mechanism_pathway:
- 'Step 1: Initial immune challenge induces trained immunity through epigenetic and
  metabolic reprogramming of innate immune cells'
- 'Step 2: Memory-like features develop in innate immune cells with increased responsiveness
  to subsequent challenges'
- 'Step 3: Enhanced inflammatory capacity enables more rapid and robust immune responses
  upon re-exposure'
- 'Step 4: Improved immune response capacity provides protection against secondary
  infections'
evidence:
  quality_rating: C
  n_studies: null
  primary_citation: 'Trim Lajqi et al. 2023. "Training vs. Tolerance: The Yin/Yang
    of the Innate Immune System." *Biomedicines*. https://doi.org/10.3390/biomedicines11030766'
last_updated: '2025-12-02'
version: '1.0'
llm_metadata:
  extracted_by: claude-sonnet-4-5-20250929
  extraction_date: '2025-12-02T18:12:07.108897'
  batch_id: msgbatch_01AKnPJgzm7Fk9qubgAz9GaD
moderators:
- name: appropriateness_of_induction
  direction: strengthens
  strength: strong
  description: Appropriate induction of trained immunity strengthens protective effects
    against secondary infections, while inappropriate induction may lead to inflammatory
    pathology
_source_file: /Users/mauriceelhelou/Library/CloudStorage/OneDrive-HarvardUniversity/New
  folder (2)/healthsystems/mechanism-bank/mechanisms/biological/trained_immunity_induction_to_secondary_infection_protection.yaml
_category: biological
