"""Initial migration - nodes, mechanisms, geographic_contexts

Revision ID: 516074b986c0
Revises: 
Create Date: 2025-11-17 20:04:48.210708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516074b986c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geographic_contexts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geography_type', sa.String(), nullable=False),
    sa.Column('fips_code', sa.String(), nullable=True),
    sa.Column('census_tract', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('medicaid_expansion', sa.Boolean(), nullable=True),
    sa.Column('medicaid_eligibility_threshold', sa.Integer(), nullable=True),
    sa.Column('housing_code_enforcement_strength', sa.String(), nullable=True),
    sa.Column('rental_assistance_availability', sa.String(), nullable=True),
    sa.Column('minimum_wage', sa.Float(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('poverty_rate', sa.Float(), nullable=True),
    sa.Column('median_income', sa.Float(), nullable=True),
    sa.Column('uninsurance_rate', sa.Float(), nullable=True),
    sa.Column('racial_composition', sa.JSON(), nullable=True),
    sa.Column('baseline_mortality_rate', sa.Float(), nullable=True),
    sa.Column('baseline_asthma_rate', sa.Float(), nullable=True),
    sa.Column('baseline_diabetes_rate', sa.Float(), nullable=True),
    sa.Column('baseline_ed_utilization', sa.Float(), nullable=True),
    sa.Column('housing_quality_index', sa.Float(), nullable=True),
    sa.Column('air_quality_index', sa.Float(), nullable=True),
    sa.Column('walkability_index', sa.Float(), nullable=True),
    sa.Column('data_year', sa.Integer(), nullable=True),
    sa.Column('data_sources', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geographic_contexts_id'), 'geographic_contexts', ['id'], unique=False)
    op.create_index(op.f('ix_geographic_contexts_state'), 'geographic_contexts', ['state'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('measurement_method', sa.Text(), nullable=True),
    sa.Column('typical_range', sa.String(), nullable=True),
    sa.Column('data_sources', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_category'), 'nodes', ['category'], unique=False)
    op.create_index(op.f('ix_nodes_id'), 'nodes', ['id'], unique=False)
    op.create_table('mechanisms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('from_node_id', sa.String(), nullable=False),
    sa.Column('to_node_id', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('mechanism_pathway', sa.JSON(), nullable=True),
    sa.Column('evidence_quality', sa.String(), nullable=False),
    sa.Column('evidence_n_studies', sa.Integer(), nullable=False),
    sa.Column('evidence_primary_citation', sa.Text(), nullable=False),
    sa.Column('evidence_supporting_citations', sa.JSON(), nullable=True),
    sa.Column('evidence_doi', sa.String(), nullable=True),
    sa.Column('varies_by_geography', sa.Boolean(), nullable=True),
    sa.Column('variation_notes', sa.Text(), nullable=True),
    sa.Column('relevant_geographies', sa.JSON(), nullable=True),
    sa.Column('moderators', sa.JSON(), nullable=True),
    sa.Column('structural_competency_root_cause', sa.String(), nullable=True),
    sa.Column('structural_competency_avoids_victim_blaming', sa.Boolean(), nullable=True),
    sa.Column('structural_competency_equity_implications', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('validated_by', sa.JSON(), nullable=True),
    sa.Column('llm_extracted_by', sa.String(), nullable=True),
    sa.Column('llm_extraction_date', sa.DateTime(), nullable=True),
    sa.Column('llm_extraction_confidence', sa.String(), nullable=True),
    sa.Column('llm_prompt_version', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('limitations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['from_node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['to_node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mechanisms_category'), 'mechanisms', ['category'], unique=False)
    op.create_index(op.f('ix_mechanisms_from_node_id'), 'mechanisms', ['from_node_id'], unique=False)
    op.create_index(op.f('ix_mechanisms_id'), 'mechanisms', ['id'], unique=False)
    op.create_index(op.f('ix_mechanisms_to_node_id'), 'mechanisms', ['to_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mechanisms_to_node_id'), table_name='mechanisms')
    op.drop_index(op.f('ix_mechanisms_id'), table_name='mechanisms')
    op.drop_index(op.f('ix_mechanisms_from_node_id'), table_name='mechanisms')
    op.drop_index(op.f('ix_mechanisms_category'), table_name='mechanisms')
    op.drop_table('mechanisms')
    op.drop_index(op.f('ix_nodes_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_category'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_geographic_contexts_state'), table_name='geographic_contexts')
    op.drop_index(op.f('ix_geographic_contexts_id'), table_name='geographic_contexts')
    op.drop_table('geographic_contexts')
    # ### end Alembic commands ###
