"""add_scale_column_to_nodes

Revision ID: 5cf6a1974760
Revises: 516074b986c0
Create Date: 2025-11-23 17:38:00.377469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf6a1974760'
down_revision: Union[str, Sequence[str], None] = '516074b986c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add scale column with default value for existing rows
    op.add_column('nodes', sa.Column('scale', sa.Integer(), nullable=True))
    # Update existing rows to have scale=4 (individual level as default)
    op.execute("UPDATE nodes SET scale = 4 WHERE scale IS NULL")
    # Make column non-nullable after backfilling
    op.alter_column('nodes', 'scale', nullable=False)
    # Add check constraint
    op.create_check_constraint('scale_range', 'nodes', 'scale >= 1 AND scale <= 7')
    # Create index
    op.create_index(op.f('ix_nodes_scale'), 'nodes', ['scale'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodes_scale'), table_name='nodes')
    op.drop_constraint('scale_range', 'nodes', type_='check')
    op.drop_column('nodes', 'scale')
    # ### end Alembic commands ###
